# Generated by Django 5.2.7 on 2025-11-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_cliententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('use_cases', models.JSONField(blank=True, default=list)),
                ('who', models.CharField(blank=True, max_length=200)),
                ('doc', models.URLField(blank=True)),
                ('internal_runbook', models.URLField(blank=True)),
                ('cliq_channel', models.URLField(blank=True)),
                ('access', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='app_icons/')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('help_contact', models.JSONField(blank=True, default=dict)),
                ('popularity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliententry',
            name='domain',
        ),
        migrations.AddField(
            model_name='cliententry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_entries', to='directory.department'),
        ),
        migrations.AddField(
            model_name='cliententry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_entries', to='directory.location'),
        ),
    ]
