# Generated by Django 5.2.7 on 2025-11-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_zohoapp_remove_cliententry_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoapp',
            name='guide_url',
            field=models.URLField(blank=True, help_text='YouTube / Loom / direct mp4 link for the app guide', null=True, verbose_name='Guide video URL'),
        ),
    ]
