# Generated by Django 5.2.7 on 2025-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_zohoapp_guide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoapp',
            name='guide_file',
            field=models.FileField(blank=True, help_text='Upload MP4 file (stored in MEDIA_ROOT/guides/)', null=True, upload_to='guides/'),
        ),
        migrations.AlterField(
            model_name='zohoapp',
            name='guide_url',
            field=models.URLField(blank=True, help_text='YouTube / Loom link', null=True, verbose_name='Guide video URL'),
        ),
    ]
