# Generated by Django 5.2.7 on 2025-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_zohoapp_guide_file_alter_zohoapp_guide_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoapp',
            name='guide_file',
            field=models.FileField(blank=True, help_text='Upload MP4', null=True, upload_to='guides/'),
        ),
        migrations.AlterField(
            model_name='zohoapp',
            name='guide_url',
            field=models.URLField(blank=True, help_text='YouTube / Loom / direct mp4 link', null=True),
        ),
    ]
